"""Settings read from the environment (/etc/intelreach-crm.env on the server)."""
import os
from pathlib import Path


def env(key, default=""):
    return os.environ.get(key, default).strip()


DB_PATH = env("CRM_DB", "/var/lib/intelreach-crm/crm.db")

# git commit of the running code (deploy/install.sh writes it) – shown in Admin and /api/health
_vf = Path(__file__).resolve().parent.parent / "VERSION"
VERSION = _vf.read_text().strip() if _vf.exists() else "dev"
PUBLIC_URL = env("CRM_PUBLIC_URL", "https://dialer.intelreach.com").rstrip("/")
COOKIE_SECURE = env("CRM_COOKIE_SECURE", "1") == "1"

# Shared secret the Asterisk dialplan sends with every CURL() to /ast/*
AST_SECRET = env("CRM_AST_SECRET")

# Twilio account that owns the number – fallback only: Admin → Integrations → Twilio wins
TWILIO_SID = env("TWILIO_ACCOUNT_SID")
TWILIO_TOKEN = env("TWILIO_AUTH_TOKEN")

# Where browsers register (the existing IntelReach Asterisk)
SIP_WSS = env("CRM_SIP_WSS", "wss://pbx.intelreach.com/ws")
SIP_DOMAIN = env("CRM_SIP_DOMAIN", "pbx.intelreach.com")
# Where Twilio sends incoming calls (<Dial><Sip>) – Asterisk's public UDP 5060
SIP_INBOUND_URI = env("CRM_SIP_INBOUND", "sip:crm@76.13.179.69:5060;transport=udp")

# coturn "use-auth-secret" (same value as /etc/intelreach.env TURN_SECRET)
TURN_SECRET = env("TURN_SECRET")
TURN_HOST = env("TURN_HOST", "turn.intelreach.com")

# Agent SIP extensions generated by scripts/gen_agent_pool.py
POOL_FILE = env("CRM_POOL_FILE", "/etc/intelreach-crm/agent_pool.json")

SESSION_DAYS = int(env("CRM_SESSION_DAYS", "14") or 14)
# An agent counts as online for incoming calls if the browser pinged this recently
ONLINE_SECONDS = 75

# Encrypts provider API keys stored in the database (Fernet key, generated by install.sh)
SECRET_KEY = env("CRM_SECRET_KEY")
# Asterisk MixMonitor writes human-call recordings here (CRM user is in the asterisk group)
RECORDINGS_DIR = env("CRM_RECORDINGS", "/var/spool/asterisk/monitor/crm")
# Voicemail audio, downloaded AI-call recordings
MEDIA_DIR = env("CRM_MEDIA", "/var/lib/intelreach-crm/media")
WS_PUBLIC_URL = PUBLIC_URL.replace("https://", "wss://").replace("http://", "ws://")
# Background campaign dialer (off in tests)
RUN_DIALER = env("CRM_RUN_DIALER", "1") == "1"
# SIP trunks are set up in Admin → SIP trunks; the CRM writes pjsip_trunks.conf + trunk_ips.txt here
# and the root unit intelreach-crm-trunks.path reloads Asterisk / the firewall when they change.
TRUNKS_DIR = env("CRM_TRUNKS_DIR", "/etc/intelreach-crm/asterisk")
# AI agents over the SIP trunks: Asterisk's AudioSocket connects here (127.0.0.1 only),
# outbound AI calls are started with call files in Asterisk's spool
AUDIOSOCKET_PORT = int(env("CRM_AUDIOSOCKET_PORT", "8045") or 8045)
AST_SPOOL = env("CRM_AST_SPOOL", "/var/spool/asterisk/outgoing")
# call files are written here first (same file system), then moved into the spool in one step
AST_SPOOL_TMP = env("CRM_AST_SPOOL_TMP", "/var/spool/asterisk/crm-tmp")
