#!/usr/bin/env python3
"""Generate SIP extensions for CRM agents (one per agent, assigned by the CRM).

    python3 scripts/gen_agent_pool.py --from 2001 --count 50 \
        --conf /etc/asterisk/pjsip_crm_agents.conf --json /etc/intelreach-crm/agent_pool.json

Existing passwords in the JSON file are kept, so running it again only adds lines.
Reload Asterisk afterwards:  asterisk -rx "module reload res_pjsip.so"
"""
import argparse
import json
import os
import secrets

ap = argparse.ArgumentParser()
ap.add_argument("--from", dest="start", type=int, default=2001)
ap.add_argument("--count", type=int, default=50)
ap.add_argument("--conf", default="/etc/asterisk/pjsip_crm_agents.conf")
ap.add_argument("--json", default="/etc/intelreach-crm/agent_pool.json")
a = ap.parse_args()

old = {}
if os.path.exists(a.json):
    with open(a.json, encoding="utf-8") as f:
        old = {str(p["ext"]): p["password"] for p in json.load(f)}

pool = [{"ext": str(e), "password": old.get(str(e)) or secrets.token_hex(12)} for e in range(a.start, a.start + a.count)]
for ext, pw in old.items():
    if ext not in {p["ext"] for p in pool}:
        pool.append({"ext": ext, "password": pw})
pool.sort(key=lambda p: int(p["ext"]))

lines = ["; Generated by intelreach-crm/scripts/gen_agent_pool.py – CRM agent phones.",
         "; Templates are in pjsip_crm.conf. Included via: #include pjsip_crm_agents.conf", ""]
for p in pool:
    e = p["ext"]
    lines += [f"[{e}](crm-agent)", f"auth={e}", f"aors={e}", f'callerid="CRM {e}" <{e}>', "",
              f"[{e}](crm-agent-auth)", f"username={e}", f"password={p['password']}", "",
              f"[{e}](crm-agent-aor)", ""]

os.makedirs(os.path.dirname(a.json) or ".", exist_ok=True)
with open(a.conf, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
with open(a.json, "w", encoding="utf-8") as f:
    json.dump(pool, f, indent=1)
os.chmod(a.json, 0o640)
print(f"{len(pool)} agent lines: {pool[0]['ext']}–{pool[-1]['ext']} -> {a.conf}, {a.json}")
